
const menu = [
  {
    id: 1,
    title: "Osh",
    category: "breakfast",
    price: 1.8,
    img: './images/osh.jpg',
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque?Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 2,
    title: "Manti",
    category: "breakfast",
    price: 0.5,
    img: "./images/manti.png",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora. ",
  },
  {
    id: 3,
    title: "Norin",
    category: "breakfast",
    price: 2.3,
    img: "./images/norin.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 4,
    title: "Qozon kabob",
    category: "breakfast",
    price: 2.3,
    img: "./images/qozon-kabob.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 5,
    title: "Do'lma",
    category: "breakfast",
    price: 0.7,
    img: "./images/dolma.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 6,
    title: "Somsa",
    category: "breakfast",
    price: 0.5,
    img: "./images/somsa.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 11,
    title: "Sho'rva",
    category: "breakfast",
    price: 1.8,
    img: "./images/shorva.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 7,
    title: "Oliviya",
    category: "salad",
    price: 1,
    img: "./images/oliviya.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 8,
    title: "Mujiskiy kapriz",
    category: "salad",
    price: 1.3,
    img: "./images/mujiskoy.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 9,
    title: "Salat",
    category: "salad",
    price: 1.4,
    img: "./images/salat2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 10,
    title: "Pentuza",
    category: "salad",
    price: 0.8,
    img: "./images/pentuza.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 12,
    title: "Shirinlik",
    category: "shirinlik",
    price: 2,
    img: "./images/shirinlik.png",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 13,
    title: "Shirinlik",
    category: "shirinlik",
    price: 1,
    img: "./images/shirinlik3.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
  {
    id: 14,
    title: "Pomidor Salat",
    category: "salad",
    price: 1.6,
    img: "./images/pomidor.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus dolorem a cum. Ad officia fuga enim atque! Repudiandae laborum recusandae, ullam labore error aperiam ad, dolores, reiciendis incidunt voluptatum atque? Suscipit nemo quidem neque dolorum provident veniam, aliquam a! Reprehenderit ab, debitis fuga et rerum cupiditate. Repellendus corporis fugiat magni rem tempora.",
  },
]
export default menu;